apiVersion: apps/v1
kind: Deployment
metadata: 
  name: despliegue-taller
spec:
  selector:
    matchLabels:
      app: taller
  replicas: 1
  template:
    metadata:
      labels:
        app: taller
    spec:
      containers:
        - name: coches
          image: asdiaz/aos_subsistema2:latest
          imagePullPolicy: Always
        - name: notificaciones
          image: jvidalc/aos_subsistema4_notificaciones:latest
          imagePullPolicy: Always




