version: "3"
services:

  ss1_clientes:
    image: zcj583/ss1-onlyflask
    ports:
      - "8080:8080"
    networks: 
      - taller

  ss2_vehiculos:
    image: asdiaz/aos_subsistema2:2.4
    ports:
      - "8081:8080"
    networks: 
      - taller
  
  ss3_trabajos:
    image: migue9b/trabajos:latest
    ports:
      - "8082:8080"
    networks: 
      - taller
  
  ss4_notificaciones:
    image: jvidalc/aos_subsistema4_notificaciones
    ports:
      - "8083:8080"
    networks:
      - ss4-mysql
      - taller
    depends_on:
      - mysqldb
  
  ss5_facturas:
    image: rugana90/aos-ss5:0.5
    ports:
      - "8084:8080"
    networks: 
      - taller

  ss6_recambios:
    image: clatange/aos:latest
    ports:
      - "8085:8080"
    networks: 
      - taller
  
  mysqldb:
    image: mysql:8
    restart: always
    networks:
      - ss4-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty
      - MYSQL_DATABASE=aos4
      - MYSQL_USER=qwerty
      - MYSQL_PASSWORD=qwerty
    volumes:
      - db_data:/var/lib/mysql
      - ./dbdump:/docker-entrypoint-initdb.d
    
networks:
  ss4-mysql:
  taller:

volumes:
  db_data: