version: "3"
services:
  spring:
    image: jvidalc/aos_subsistema4_notificaciones
    ports:
      - "8080:8080"
    networks:
      - spring-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    restart: always
    networks:
      - spring-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty
      - MYSQL_DATABASE=aos4
      - MYSQL_USER=qwerty
      - MYSQL_PASSWORD=qwerty
    volumes:
      - db_data:/var/lib/mysql
      - ./dbdump:/docker-entrypoint-initdb.d

networks:
  spring-mysql:

volumes:
  db_data: