#DEPLOYMENTS TALLER
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ss1-clientes
spec:
  selector:
    matchLabels:
      app: ss1-clientes
      role: clientes
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ss1-clientes
        role: clientes
        tier: backend
    spec:
      containers:
        - name: ss1-clientes
          image: zcj583/ss1-onlyflask
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
          - containerPort: 8080

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ss2-vehiculos
spec:
  selector:
    matchLabels:
      app: ss2-vehiculos
      role: vehiculos
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ss2-vehiculos
        role: vehiculos
        tier: backend
    spec:
      containers:
        - name: ss2-vehiculos
          image: asdiaz/aos_subsistema2:2.4
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
          - containerPort: 8080

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ss3-trabajos
spec:
  selector:
    matchLabels:
      app: ss3-trabajos
      role: trabajos
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ss3-trabajos
        role: trabajos
        tier: backend
    spec:
      containers:
        - name: ss3-trabajos
          image: albertozuga/aos-ss3:1.0.2
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
          - containerPort: 8080

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ss4-notificaciones
spec:
  selector:
    matchLabels:
      app: ss4-notificaciones
      role: notificaciones
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ss4-notificaciones
        role: notificaciones
        tier: backend
    spec:
      containers:
        - name: ss4-notificaciones
          image: jvidalc/aos_subsistema4_notificaciones:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
          - containerPort: 8080

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ss5-facturas
spec:
  selector:
    matchLabels:
      app: ss5-facturas
      role: facturas
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ss5-facturas
        role: facturas
        tier: backend
    spec:
      containers:
        - name: ss5-facturas
          image: rugana90/aos-ss5:0.5
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
          - containerPort: 8080

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ss6-recambios
spec:
  selector:
    matchLabels:
      app: ss6-recambios
      role: recambios
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: ss6-recambios
        role: recambios
        tier: backend
    spec:
      containers:
        - name: ss6-recambios
          image: clatange/aos:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
          - containerPort: 8080
          
#SERVICES
---
apiVersion: v1
kind: Service
metadata:
  name: ss1-clientes
  labels:
    app: ss1-clientes
    role: clientes
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8080       
    targetPort: 8080  
  selector:           
    app: ss1-clientes
    role: clientes
    tier: backend

---
apiVersion: v1
kind: Service
metadata:
  name: ss2-vehiculos
  labels:
    app: ss2-vehiculos
    role: vehiculos
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8081        
    targetPort: 8080  
  selector:           
    app: ss2-vehiculos
    role: vehiculos
    tier: backend
        
---
apiVersion: v1
kind: Service
metadata:
  name: ss3-trabajos
  labels:
    app: ss3-trabajos
    role: trabajos
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8082       
    targetPort: 8080  
  selector:           
    app: ss3-trabajos
    role: trabajos
    tier: backend

---
apiVersion: v1
kind: Service
metadata:
  name: ss4-notificaciones
  labels:
    app: ss4-notificaciones
    role: notificaciones
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8083       
    targetPort: 8080  
  selector:           
    app: ss4-notificaciones
    role: notificaciones
    tier: backend

---
apiVersion: v1
kind: Service
metadata:
  name: ss5-facturas
  labels:
    app: ss5-facturas
    role: facturas
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8084       
    targetPort: 8080  
  selector:           
    app: ss5-facturas
    role: facturas
    tier: backend

---
apiVersion: v1
kind: Service
metadata:
  name: ss6-recambios
  labels:
    app: ss6-recambios
    role: recambios
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8084       
    targetPort: 8080  
  selector:           
    app: ss6-recambios
    role: recambios
    tier: backend

#MYSQL PERSIST VOLUME
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

#DEPLOYMENT MYSQL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      containers:
      - image: mysql:8
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: qwerty
        - name: MYSQL_DATABASE
          value: aos4
        - name: MYSQL_USER
          value: qwerty
        - name: MYSQL_PASSWORD
          value: qwerty
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim